# ./roles/dnf/tasks/main.yml
---
- name: Ensure DNF packages are present
  ansible.builtin.dnf:
    name: "{{ dnf_packages }}"
    state: present
  when: profile_state == "provision"

- name: Ensure DNF packages are absent
  ansible.builtin.dnf:
    name: "{{ dnf_packages }}"
    state: absent
  when: profile_state == "clean"
