# ./configs/setup/main.yml
---
- name: Configure firewall
  ansible.builtin.import_tasks: firewall/main.yml

- name: Configure networking
  ansible.builtin.import_tasks: networking/main.yml

- name: Configure subdomains
  ansible.builtin.import_tasks: subdomains/main.yml
