# ./roles/flatpak/tasks/main.yml
---
- name: Ensure flatpak package is installed
  become: true
  ansible.builtin.dnf:
    name: flatpak
    state: present
  when: profile_state == "provision"

- name: Add Flathub remote if not present
  become: true
  ansible.builtin.command: >
    flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  args:
    warn: false
  when:
    - profile_state == "provision"

- name: Install flatpak packages
  become: true
  ansible.builtin.command: >
    flatpak install -y --noninteractive {{ item }}
  loop: "{{ flatpak_packages | default([]) }}"
  when:
    - profile_state == "provision"
    - flatpak_packages is defined and flatpak_packages | length > 0

- name: Remove flatpak packages
  become: true
  ansible.builtin.command: >
    flatpak uninstall -y {{ item }}
  loop: "{{ flatpak_remove_packages | default([]) }}"
  when:
    - profile_state == "clean"
    - flatpak_remove_packages is defined and flatpak_remove_packages | length > 0
