# ./roles/rpm/tasks/main.yml
---
- name: Add RPM repositories
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "/etc/yum.repos.d/{{ item.name }}.repo"
  loop: "{{ rpm_packages | default([]) }}"
  when: profile_state == "provision"

- name: Remove RPM repositories
  ansible.builtin.file:
    path: "/etc/yum.repos.d/{{ item.name }}.repo"
    state: absent
  loop: "{{ rpm_packages | default([]) }}"
  when: profile_state == "clean"
