# ./roles/rpm/tasks/main.yml
---
- name: Add RPM repositories
  become: true
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "/etc/yum.repos.d/{{ item.name }}.repo"
    mode: '0644'
    validate_certs: yes
  loop: "{{ rpm_packages | default([]) }}"
  when:
    - profile_state == "provision"
    - item.url is defined and item.url | length > 0

# - name: Import GPG keys for RPM repositories          # redundant, removed for clarity
#   become: true
#   ansible.builtin.rpm_key:
#     state: present
#     key: "{{ item.gpgkey }}"
#   loop: "{{ rpm_packages | default([]) }}"
#   when:
#     - profile_state == "provision"
#     - item.gpgkey is defined

- name: Remove RPM repositories
  become: true
  ansible.builtin.file:
    path: "/etc/yum.repos.d/{{ item.name }}.repo"
    state: absent
  loop: "{{ rpm_packages | default([]) }}"
  when: profile_state == "clean"

# # Bring extra apps
# - import_tasks: 