---
# inventories/neptune/host_vars/neptune/02_secrets.yml

# Postgresql
postgresql_users:
  - name: "{{ lookup('env', 'DB_USER') }}"
    password: "{{ lookup('env', 'DB_PASSWORD') }}"
    role_attr_flags: ""