---
# playbooks/build-saturn.yml
- name: Build Saturn profile
  hosts: saturn
  become: true
  gather_facts: true
  vars_files:
    - "../inventories/group_vars/saturn.yml"
  vars:
    repo_root: "{{ playbook_dir }}/.."

  roles:
    - dnf
    - rpm
    - flatpak

  tasks:
    - name: Apply setup configs
      ansible.builtin.import_playbook: "{{ repo_root }}/configs/saturn/setup/main.yml"

    - name: Apply system configs
      ansible.builtin.import_playbook: "{{ repo_root }}/configs/saturn/system/main.yml"

    - name: Apply user configs
      ansible.builtin.import_playbook: "{{ repo_root }}/configs/saturn/user/main.yml"
