---
- name: Build Neptune profile
  hosts: neptune
  become: true
  gather_facts: true
  vars_files:
    - "../inventories/group_vars/neptune.yml"
  vars:
    repo_root: "{{ playbook_dir }}/.."

  roles:
    - dnf
    - rpm
    - flatpak

  tasks:
    - name: Apply setup configs
      ansible.builtin.import_playbook: "../configs/neptune/setup/main.yml"

    - name: Apply system configs
      ansible.builtin.import_playbook: "../configs/neptune/system/main.yml"

    - name: Apply user configs
      ansible.builtin.import_playbook: "../configs/neptune/user/main.yml"
