# ./playbooks/clean-system.yml
---
- name: Clean profile-managed components
  hosts: "{{ profile_target | default('saturn') }}"
  become: true
  gather_facts: true
  vars_files:
    - "../inventories/group_vars/{{ profile_target | default('saturn') }}.yml"
  vars:
    profile_state: clean
    repo_root: "{{ playbook_dir }}/.."

  roles:
    - dnf
    - rpm
    - flatpak
    - system_setup
    - system_configs
    - user_configs
